### ISSUE TITLE
[Bug] TrueNAS graphs not returning values

### ISSUE THREAD

**Issue by anschein** [tomaae/homeassistant-truenas#16]
After update HA 2022.4.4 to 2022.4.5,error logged and component can't load.
log as:
Error setting up entry TrueNAS for truenas
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/truenas/__init__.py", line 29, in async_setup_entry
    await controller.async_update()
  File "/config/custom_components/truenas/truenas_controller.py", line 115, in async_update
    await self.hass.async_add_executor_job(self.get_systemstats)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/truenas/truenas_controller.py", line 231, in get_systemstats
    max(tmp_graph[i]["aggregations"]["mean"]), 1
TypeError: '>' not supported between instances of 'NoneType' and 'float'

**Comment by tomaae** [comment]
This is not related to HA update, something went wrong on TrueNAS side.
Check in TrueNAS if graphs are working fine. If you want to know which one exactly is causing the issue, you can run the integration in debug.

**Comment by anschein** [comment]
> This is not related to HA update, something went wrong on TrueNAS side. Check in TrueNAS if graphs are working fine. If you want to know which one exactly is causing the issue, you can run the integration in debug.
TrueNas graphs working fine,I turned debug mode and log says that some value is None
Maybe because I remove one CPU from my R720XD,but sorry to ask,How to fix this problem?
log:
2022-04-18 13:07:10 DEBUG (SyncWorker_9) [custom_components.truenas.truenas_api] TrueNAS 192.168.5.81 query response: [{'name': 'load', 'identifier': None, 'data': [[2.70737072, 3.07579024, 3.03644756], [2.708153372, 3.060657278, 3.033552426], [2.750531456, 3.058685312, 3.032895104], [2.619734216, 3.023552444, 3.02], [2.667370552, 3.019342638, 3.016447546], [2.533161056, 2.98223783, 3.002895132], [2.405132871, 2.935790212, 2.986447553]], 'start': 1650258340, 'end': 1650258400, 'step': 10, 'legend': ['load_shortterm', 'load_midterm', 'load_longterm'], 'aggregations': {'min': [2.405132871, 2.935790212, 2.986447553], 'mean': [2.627350606142857, 3.0222937077142857, 3.018383617285714], 'max': [2.750531456, 3.07579024, 3.03644756]}}, {'name': 'cputemp', 'identifier': None, 'data': [[43.0, 44.0, 47.0, 48.0, 47.0, 39.0, None, None, None, None, None, None], [43.6751516, 44.6751464, 46.662432, 48.337567, 46.662434, 39.6751294, None, None, None, None, None, None], [45.0, 46.0, 46.0, 49.0, 46.0, 41.0, None, None, None, None, None, None], [45.0, 46.0, 46.0, 49.0, 46.0, 41.0, None, None, None, None, None, None], [45.0, 46.0, 46.0, 49.0, 46.0, 41.0, None, None, None, None, None, None], [45.0, 46.0, 46.0, 49.0, 46.0, 41.0, None, None, None, None, None, None], [45.0, 46.0, 46.0, 49.0, 46.0, 41.0, None, None, None, None, None, None]], 'start': 1650258340, 'end': 1650258400, 'step': 10, 'legend': ['cputemp0', 'cputemp1', 'cputemp2', 'cputemp3', 'cputemp4', 'cputemp5', 'cputemp6', 'cputemp7', 'cputemp8', 'cputemp9', 'cputemp10', 'cputemp11'], 'aggregations': {'min': [43.0, 44.0, 46.0, 48.0, 46.0, 39.0, None, None, None, None, None, None], 'mean': [44.52502165714286, 45.52502091428571, 46.23749028571429, 48.76250957142857, 46.23749057142857, 40.525018485714284, None, None, None, None, None, None], 'max': [45.0, 46.0, 47.0, 49.0, 47.0, 41.0, None, None, None, None, None, None]}}, {'name': 'cpu', 'identifier': None, 'data': [[0.0, 3.7976728018, 15.788370449, 0.0, 80.413956749], [0.0, 6.4176580345, 16.261273833, 0.0, 77.321068133], [0.0, 5.8548556748, 12.627101038, 0.0, 81.518043287], [0.0, 11.120777569, 12.355910996, 0.0, 76.523311435], [0.0, 5.1240141514, 12.264367308, 0.0, 82.61161854], [0.0, 4.1106095463, 12.194523243, 0.0, 83.694867211]], 'start': 1650258350, 'end': 1650258400, 'step': 10, 'legend': ['interrupt', 'system', 'user', 'nice', 'idle'], 'aggregations': {'min': [0.0, 3.7976728018, 12.194523243, 0.0, 76.523311435], 'mean': [0.0, 6.0709312962999995, 13.581924477833333, 0.0, 80.34714422583333], 'max': [0.0, 11.120777569, 16.261273833, 0.0, 83.694867211]}}, {'name': 'arcsize', 'identifier': None, 'data': [[65402421769.0, 0.0], [65417222319.0, 0.0], [65424326592.0, 0.0], [65441235269.0, 0.0], [65455451367.0, 0.0], [65472375210.0, 0.0]], 'start': 1650258350, 'end': 1650258400, 'step': 10, 'legend': ['cache_size-arc_value', 'cache_size-L2_value'], 'aggregations': {'min': [65402421769.0, 0.0], 'mean': [65435505421.0, 0.0], 'max': [65472375210.0, 0.0]}}, {'name': 'arcratio', 'identifier': None, 'data': [[99.865694309, None], [99.995883283, None], [99.9995, None], [99.999287515, None], [99.997695884, None], [99.996704122, None]], 'start': 1650258350, 'end': 1650258400, 'step': 10, 'legend': ['cache_ratio-arc_value', 'cache_ratio-L2_value'], 'aggregations': {'min': [99.865694309, None], 'mean': [99.9757941855, None], 'max': [99.9995, None]}}]
2022-04-18 13:07:11 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry TrueNAS for truenas
File "/config/custom_components/truenas/__init__.py", line 29, in async_setup_entry
File "/config/custom_components/truenas/truenas_controller.py", line 115, in async_update
File "/config/custom_components/truenas/truenas_controller.py", line 231, in get_systemstats

**Comment by tomaae** [comment]
it is reporting 12 cores, half of them as None.
this is something I'm not able to even attempt to replicate, so not sure how truenas handles it.
did you removed it using hotswap without reboot?
if you rebooted since, could you send me  a screenshot of you cpu tempeture graph from both dashboard and graphs page?

**Comment by tomaae** [comment]
You can test master to see if it work for you.

**Comment by anschein** [comment]
> You can test master to see if it work for you.


After remove CPU,reboot system like 2~3 times,still same problem.
![image](https://user-images.githubusercontent.com/49552476/163784613-2d23ba92-cbc7-4cae-a25e-ec4869a3445e.png)

master works!
Thanks a lot
Meanwhile I'm going to switch back to v1.0.2 and reboot my system from cold boot to test

**Comment by anschein** [comment]
Cold boot bot work,switch back to master looks fine.

**Comment by tomaae** [comment]
hmm, most likely a bug or something left over in rrd database. its not really critical, so no need to dive deeper into truenas.
imo, could be also that it reports number of threads but shows only sensors for number of cores for this type of CPU and graph above just extrapolates temperature of core into 2 threads. Mine is reported correctly, but its also a lot newer.
this workaround is perfectly fine tho, it can solve different issues too. so I leave it in place. for integration needs, which only takes into consideration highest temperature, it does not matter at all.
next release will have this fix included.
