### ISSUE TITLE
[Bug] Exception in async_update_controller when dispatching 'update_sensors': custom_components.portainer.coordinator.PortainerCoordinator

### ISSUE THREAD

**Issue by u2597511** [tomaae/homeassistant-truenas#169]
## Describe the issue
Exception in async_update_controller when dispatching 'update_sensors': custom_components.portainer.coordinator.PortainerCoordinator

## How to reproduce the issue
Add TrueNAS and Portainer integration.

## Software versions
 - Home Assistant version: 2024.8.3
 - TrueNAS integration version: 1.2..5
 - TrueNAS version: TrueNAS-13.0-U6.2
 - Portainer integration version: 1.0.2
 - Portainer Community Edition 2.19.5

## Traceback/Error logs
```
2024-08-30 10:46:01.764 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update_controller when dispatching 'update_sensors': (<custom_components.portainer.coordinator.PortainerCoordinator object at 0x7f71513da0>,)
Traceback (most recent call last):
  File "/config/custom_components/truenas/entity.py", line 68, in async_update_controller
    data = coordinator.data[entity_description.data_path]
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'system_info'

2024-08-30 10:46:31.633 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update_controller when dispatching 'update_sensors': (<custom_components.portainer.coordinator.PortainerCoordinator object at 0x7f71513da0>,)
Traceback (most recent call last):
  File "/config/custom_components/truenas/entity.py", line 68, in async_update_controller
    data = coordinator.data[entity_description.data_path]
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'system_info'

2024-08-30 10:46:31.656 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update_controller when dispatching 'update_sensors': (<custom_components.portainer.coordinator.PortainerCoordinator object at 0x7f71513da0>,)
Traceback (most recent call last):
  File "/config/custom_components/truenas/entity.py", line 68, in async_update_controller
    data = coordinator.data[entity_description.data_path]
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'pool'
```

**Comment by raetha** [comment]
I'm experiencing this same issue. Was there any resolution besides the auto-close?

**Comment by u2597511** [comment]
> I'm experiencing this same issue. Was there any resolution besides the auto-close?

I haven't found an answer to this question anywhere. Apparently, no one but us is interested. :(

**Comment by raetha** [comment]
I believe the issue is actually in the Portainer integration, though honestly it seems like an HA bug that allows one integration to cause this for others. Not idea the right place to file it, but I don't believe it's actually a TrueNAS issue, unless they could work around whatever the Portainer one is breaking somehow. My solution was finally to just disable Portainer. I like data in HA, but Portainer wasn't important enough to keep in place.
