### ISSUE TITLE
[Bug] cannot setup integration

### ISSUE THREAD

**Issue by sezlony** [tomaae/homeassistant-truenas#185]
## Describe the issue
After upgrading to latest version the integration stopped working, lost all sensors.

## Software versions

 - Home Assistant version: core 2024.9.2
 - TrueNAS integration version: v1.3
 - TrueNAS version: TrueNAS-13.0-U4

## Diagnostics data
```
2024-11-14 16:22:36.588 DEBUG (MainThread) [custom_components.truenas.coordinator] Finished fetching Nas data in 0.221 seconds (success: False)
2024-11-14 16:23:56.768 DEBUG (SyncWorker_56) [custom_components.truenas.api] TrueNAS 192.168.1.103:4435 query: system/info, get, {}
2024-11-14 16:23:56.967 DEBUG (SyncWorker_56) [custom_components.truenas.api] TrueNAS 192.168.1.103:4435 query response: {'version': 'TrueNAS-13.0-U4', 'buildtime': {'$date': 1677542817000}, 'hostname': 'NAS', 'physmem': 17050587136, 'model': 'AMD Turion(tm) II Neo N40L Dual-Core Processor', 'cores': 2, 'loadavg': [0.08251953125, 0.06103515625, 0.06640625], 'uptime': '108 days, 20:49:33.783270', 'uptime_seconds': 9406173.783270465, 'system_serial': '5C7226P1H9', 'system_product': 'ProLiant MicroServer', 'system_product_version': None, 'license': None, 'boottime': {'$date': 1722191663000}, 'datetime': {'$date': 1731597836949}, 'birthday': {'$date': 1682465215416}, 'timezone': 'Europe/Budapest', 'system_manufacturer': 'HP', 'ecc_memory': True}
2024-11-14 16:23:56.972 DEBUG (SyncWorker_56) [custom_components.truenas.apiparser] Processing source [{'version': 'TrueNAS-13.0-U4', 'buildtime': {'$date': 1677542817000}, 'hostname': 'NAS', 'physmem': 17050587136, 'model': 'AMD Turion(tm) II Neo N40L Dual-Core Processor', 'cores': 2, 'loadavg': [0.08251953125, 0.06103515625, 0.06640625], 'uptime': '108 days, 20:49:33.783270', 'uptime_seconds': 9406173.783270465, 'system_serial': '**REDACTED**', 'system_product': 'ProLiant MicroServer', 'system_product_version': None, 'license': None, 'boottime': {'$date': 1722191663000}, 'datetime': {'$date': 1731597836949}, 'birthday': {'$date': 1682465215416}, 'timezone': 'Europe/Budapest', 'system_manufacturer': 'HP', 'ecc_memory': True}]
2024-11-14 16:23:56.972 DEBUG (SyncWorker_56) [custom_components.truenas.apiparser] Processing entry {'version': 'TrueNAS-13.0-U4', 'buildtime': {'$date': 1677542817000}, 'hostname': 'NAS', 'physmem': 17050587136, 'model': 'AMD Turion(tm) II Neo N40L Dual-Core Processor', 'cores': 2, 'loadavg': [0.08251953125, 0.06103515625, 0.06640625], 'uptime': '108 days, 20:49:33.783270', 'uptime_seconds': 9406173.783270465, 'system_serial': '**REDACTED**', 'system_product': 'ProLiant MicroServer', 'system_product_version': None, 'license': None, 'boottime': {'$date': 1722191663000}, 'datetime': {'$date': 1731597836949}, 'birthday': {'$date': 1682465215416}, 'timezone': 'Europe/Budapest', 'system_manufacturer': 'HP', 'ecc_memory': True}
2024-11-14 16:23:56.974 ERROR (MainThread) [custom_components.truenas.coordinator] Unexpected error fetching Nas data
```

## Traceback/Error logs
```
Unexpected error fetching Truenas data

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/truenas/coordinator.py", line 95, in _async_update_data
    await self.hass.async_add_executor_job(self.get_systeminfo)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/truenas/coordinator.py", line 221, in get_systeminfo
    self._version_minor = int(
                          ^^^^
ValueError: invalid literal for int() with base 10: '0-U4'
```

**Comment by tomaae** [comment]
duplicate #186
