### ISSUE TITLE
[Bug] Failed to complete setup

### ISSUE THREAD

**Issue by iriks-it** [tomaae/homeassistant-truenas#197]
## Describe the issue
When installing i ran into this error.
I tried to remove the entry and retry but sadly the same outcome.
I also tried to remove the addon, then reinstall it, but... sadly, no luck here either.

## Software versions
All fields in this sections are required.
 - Home Assistant version: core-2024.12.5
 - TrueNAS integration version: LATEST
 - TrueNAS version: 13.0-U6.4

## Traceback/Error logs
```
2024-12-30 23:10:33.711 DEBUG (MainThread) [custom_components.truenas.coordinator] Finished fetching TrueNAS data in 54.435 seconds (success: True)
2024-12-30 23:10:33.711 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry TrueNAS for truenas
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/truenas/__init__.py", line 30, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 306, in async_config_entry_first_refresh
    await self._async_refresh(
        log_failures=False, raise_on_auth_failed=True, raise_on_entry_error=True
    )
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/truenas/coordinator.py", line 97, in _async_update_data
    await self.hass.async_add_executor_job(self.get_systemstats)
asyncio.exceptions.CancelledError
```

**Comment by jacobohpea** [comment]
I believe this is realted to #191

**Comment by iriks-it** [comment]
@jacobohpea 
> I believe this is realted to #191

My install of hoas is not in docker, but in a proxmox env, i used : https://community-scripts.github.io/ProxmoxVE/scripts?id=haos-vm

**Comment by tomaae** [comment]
I will need to see debugs.

**Comment by iriks-it** [comment]
@tomaae 
> I will need to see debugs.

Where should i get them ? Let me know what to do and i'll get the logs

**Comment by tomaae** [comment]
https://github.com/tomaae/homeassistant-truenas?tab=readme-ov-file#enabling-debug

**Comment by Sawtaytoes** [comment]
I'm having similar issues.

I configured this integration a few weeks ago, and it was working just fine, but a few days ago, it said it wasn't working:

![image](https://github.com/user-attachments/assets/ac3977d1-ef66-4639-adab-6139bfdadb97)

I even deleted and re-added it, and it still failed to connect, but it must've at some point because it has devices and entities now even though it's gone back to saying it can't connect. I even tried recreating the API to no avail.

Unlike other folks on CORE, I'm on TrueNAS SCALE `v24.10.1`.

I'm seeing this in the logs:
```sh
2025-01-08 20:01:38.769 WARNING (SyncWorker_2) [custom_components.truenas.api] TrueNAS storeman unable to fetch data "update/check_available" (no_response)
2025-01-08 20:02:45.685 WARNING (SyncWorker_8) [custom_components.truenas.api] TrueNAS storeman unable to fetch data "update/check_available" (no_response)
2025-01-08 20:03:13.407 WARNING (SyncWorker_4) [custom_components.truenas.api] TrueNAS storeman unable to fetch data "update/check_available" (no_response)
2025-01-08 20:03:51.017 WARNING (SyncWorker_8) [custom_components.truenas.api] TrueNAS storeman unable to fetch data "update/check_available" (no_response)
2025-01-08 20:04:48.453 WARNING (SyncWorker_5) [custom_components.truenas.api] TrueNAS storeman unable to fetch data "update/check_available" (no_response)
```

Do you need more logs or are you receiving them already from other folks?

**Comment by FusselTV** [comment]
Same for me

**Comment by Tom60chat** [comment]
Any update ?
I have the same issue.

**Comment by tomaae** [comment]
This is an issue with Truenas. graphs are broken on truenas side.
