### ISSUE TITLE
[Bug] TrueNAS sometimes returns null value for cputemp

### ISSUE THREAD

**Issue by Geeboh** [tomaae/homeassistant-truenas#23]
Using debug logging I get this error when attempting to connect the integration for the first time:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/truenas/truenas_controller.py:231
Integration: TrueNAS (documentation, issues)
First occurred: 9:44:57 AM (2 occurrences)
Last logged: 10:13:00 AM

Error setting up entry TrueNAS for truenas
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/truenas/__init__.py", line 29, in async_setup_entry
    await controller.async_update()
  File "/config/custom_components/truenas/truenas_controller.py", line 115, in async_update
    await self.hass.async_add_executor_job(self.get_systemstats)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/truenas/truenas_controller.py", line 231, in get_systemstats
    max(tmp_graph[i]["aggregations"]["mean"]), 1
TypeError: '>' not supported between instances of 'NoneType' and 'float'

**Comment by tomaae** [comment]
Please do not open blank issue, I need additional information as per template.
At least TrueNAS version, HA version, integration version and TrueNAS platform. Include diagnostics logs if available.
In current master, it would point to cputemp. Are you running TrueNAS as VM? if so, which platform?

**Comment by Geeboh** [comment]
Sorry about that. First time I have ever logged an issue via Github. I will use the button in the integration in the future


## Describe the issue
TrueNAS integration fails initial setup with: "Error setting up entry TrueNAS for truenas"

## How to reproduce the issue
Follow getting started instructions.

## Expected behaviour
Integration connects.

## Screenshots
![image](https://user-images.githubusercontent.com/69756825/168414154-cbf5bd9d-4cf6-4423-8704-b0b8303b7b74.png)

## Software versions
 - Home Assistant version: HA Core 2022.5.3
 - TrueNAS integration version: v1.0.2
 - TrueNAS version: TrueNAS-SCALE-22.02.1

## Diagnostics data
N/A

## Traceback/Error logs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/truenas/__init__.py", line 29, in async_setup_entry
    await controller.async_update()
  File "/config/custom_components/truenas/truenas_controller.py", line 115, in async_update
    await self.hass.async_add_executor_job(self.get_systemstats)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/truenas/truenas_controller.py", line 231, in get_systemstats
    max(tmp_graph[i]["aggregations"]["mean"]), 1
TypeError: '>' not supported between instances of 'NoneType' and 'float'

## Additional context
TrueNAS is not running in a VM
CPU Min Temperature appears as "null" on TrueNAS (see screenshot). Unsure as to why.

**Comment by tomaae** [comment]
ok, so this is an issue on TrueNAS side. I will look into workaround

**Comment by tomaae** [comment]
Should be already fixed using filter none.
