### ISSUE TITLE
[Bug] failed during setup

### ISSUE THREAD

**Issue by jmilli10** [tomaae/homeassistant-truenas#26]
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/truenas/truenas_controller.py:231
Integration: TrueNAS (documentation, issues)
First occurred: 8:55:59 PM (2 occurrences)
Last logged: 8:56:20 PM

Error setting up entry TrueNAS for truenas
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/truenas/__init__.py", line 29, in async_setup_entry
    await controller.async_update()
  File "/config/custom_components/truenas/truenas_controller.py", line 115, in async_update
    await self.hass.async_add_executor_job(self.get_systemstats)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/truenas/truenas_controller.py", line 231, in get_systemstats
    max(tmp_graph[i]["aggregations"]["mean"]), 1
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'

**Comment by tomaae** [comment]
Do not delete template, I need that additional information.

**Comment by tomaae** [comment]
Seems like duplicate to #9
Try installing master

**Comment by jmilli10** [comment]
Thanks, updating to v1.1 helped as well

**Comment by tomaae** [comment]
yup, that already contains all fixes and workarounds
