### ISSUE TITLE
[Bug] Need to rreload integration after truenas reboot.

### ISSUE THREAD

**Issue by rbretmounet** [tomaae/homeassistant-truenas#48]
## Describe the issue
I am using a HASS button to call the truenas shutdown entity. But when the server is turned back on the integration does not reconnect to the API and the button no longer works unless I reload the integration.

## How to reproduce the issue
1. Turn off truenas pc
2. Turn on truenas pc
3. API no longer connected.

## Expected behavior

I expect the truenas API to reconnect with HASS

## Software versions
 - Home Assistant version: HA 2022.9.6 
 - TrueNAS integration version: v1.2.3
 - TrueNAS version: SCALE-22.02.3

**Comment by tomaae** [comment]
can you fill the versions?

**Comment by rbretmounet** [comment]
Sorry about that should be filled in now.

**Comment by tomaae** [comment]
strange. is there anything in ha log?

**Comment by rbretmounet** [comment]
How do I access the ha logs? And it may be a time-out issue. It does happen if I immediately turn the server on and off but over time it does.

**Comment by tomaae** [comment]
it is in config directory, only log HA has

**Comment by rbretmounet** [comment]
[custom_components.truenas.truenas_api] TrueNAS XXX.XXX.X.XXX unable to fetch data "system/info" (no_response)

**Comment by antontanderup** [comment]
I'm experiencing the exact same. In my case my truenas machine will be off for hours to days at a time (if that information helps).

**Comment by tomaae** [comment]
same error?

**Comment by tomaae** [comment]
I'm not able to reproduce the issue. can someone reproduce it while running debug?

**Comment by andcor** [comment]
I have just tried reproducing this issue on my setup with debug enabled and I get the following log output (filtered out what I expect is relevant) (It seems it might be another face of #55):

2022-12-01 20:33:56.722 DEBUG (SyncWorker_8) [custom_components.truenas.truenas_api] TrueNAS 192.168.1.166:444 query: system/info, get, {}
2022-12-01 20:33:56.795 DEBUG (SyncWorker_8) [custom_components.truenas.truenas_api] TrueNAS 192.168.1.166:444 query response: {'version': 'TrueNAS-SCALE-22.02.4', 'buildtime': {'$date': 1664223349000}, 'hostname': 'truenas', 'physmem': 50482282496, 'model': 'Intel(R) Xeon(R) CPU E5-1603 0 @ 2.80GHz', 'cores': 4, 'physical_cores': 4, 'loadavg': [2.29, 1.74, 1.05], 'uptime': '0:07:52.775635', 'uptime_seconds': 472.775634766, 'system_serial': '9Y49LY1', 'system_product': 'Precision T3600', 'system_product_version': '01', 'license': None, 'boottime': {'$date': 1669922764003}, 'datetime': {'$date': 1669923236779}, 'birthday': None, 'timezone': 'Europe/Copenhagen', 'system_manufacturer': 'Dell Inc.', 'ecc_memory': True}
2022-12-01 20:33:56.795 DEBUG (SyncWorker_8) [custom_components.truenas.apiparser] Processing source [{'version': 'TrueNAS-SCALE-22.02.4', 'buildtime': {'$date': 1664223349000}, 'hostname': 'truenas', 'physmem': 50482282496, 'model': 'Intel(R) Xeon(R) CPU E5-1603 0 @ 2.80GHz', 'cores': 4, 'physical_cores': 4, 'loadavg': [2.29, 1.74, 1.05], 'uptime': '0:07:52.775635', 'uptime_seconds': 472.775634766, 'system_serial': '**REDACTED**', 'system_product': 'Precision T3600', 'system_product_version': '01', 'license': None, 'boottime': {'$date': 1669922764003}, 'datetime': {'$date': 1669923236779}, 'birthday': None, 'timezone': 'Europe/Copenhagen', 'system_manufacturer': 'Dell Inc.', 'ecc_memory': True}]
2022-12-01 20:33:56.795 DEBUG (SyncWorker_8) [custom_components.truenas.apiparser] Processing entry {'version': 'TrueNAS-SCALE-22.02.4', 'buildtime': {'$date': 1664223349000}, 'hostname': 'truenas', 'physmem': 50482282496, 'model': 'Intel(R) Xeon(R) CPU E5-1603 0 @ 2.80GHz', 'cores': 4, 'physical_cores': 4, 'loadavg': [2.29, 1.74, 1.05], 'uptime': '0:07:52.775635', 'uptime_seconds': 472.775634766, 'system_serial': '**REDACTED**', 'system_product': 'Precision T3600', 'system_product_version': '01', 'license': None, 'boottime': {'$date': 1669922764003}, 'datetime': {'$date': 1669923236779}, 'birthday': None, 'timezone': 'Europe/Copenhagen', 'system_manufacturer': 'Dell Inc.', 'ecc_memory': True}
2022-12-01 20:33:56.795 DEBUG (SyncWorker_8) [custom_components.truenas.truenas_api] TrueNAS 192.168.1.166:444 query: update/check_available, post, {}
2022-12-01 20:33:57.076 DEBUG (SyncWorker_8) [custom_components.truenas.truenas_api] TrueNAS 192.168.1.166:444 query response: {'status': 'UNAVAILABLE'}
2022-12-01 20:33:57.076 DEBUG (SyncWorker_8) [custom_components.truenas.apiparser] Processing source [{'status': 'UNAVAILABLE'}]
2022-12-01 20:33:57.076 DEBUG (SyncWorker_8) [custom_components.truenas.apiparser] Processing entry {'status': 'UNAVAILABLE'}
2022-12-01 20:33:57.076 DEBUG (SyncWorker_8) [custom_components.truenas.truenas_api] TrueNAS 192.168.1.166:444 query: interface, get, {}
2022-12-01 20:33:57.142 DEBUG (SyncWorker_8) [custom_components.truenas.truenas_api] TrueNAS 192.168.1.166:444 query response: [{'id': 'enp0s25', 'name': 'enp0s25', 'fake': False, 'type': 'PHYSICAL', 'state': {'name': 'enp0s25', 'orig_name': 'enp0s25', 'description': 'enp0s25', 'mtu': 1500, 'cloned': False, 'flags': ['MULTICAST', 'UP', 'BROADCAST'], 'nd6_flags': ['HOMEADDRESS'], 'capabilities': ['tx-scatter-gather', 'tx-checksum-ip-generic', 'tx-vlan-hw-insert', 'rx-vlan-hw-parse', 'tx-generic-segmentation', 'rx-gro', 'tx-tcp-segmentation', 'tx-tcp6-segmentation', 'rx-hashing', 'rx-checksum'], 'link_state': 'LINK_STATE_UP', 'media_type': 'Ethernet', 'media_subtype': 'autoselect', 'active_media_type': 'Ethernet', 'active_media_subtype': '1000Mb/s Twisted Pair', 'supported_media': ['10baseT/Half', '10baseT/Full', '100baseT/Half', '100baseT/Full', '1000baseT/Full'], 'media_options': None, 'link_address': 'b8:ca:3a:84:b8:04', 'aliases': [{'type': 'LINK', 'address': 'b8:ca:3a:84:b8:04'}, {'type': 'INET', 'address': '192.168.1.166', 'netmask': 24, 'broadcast': '192.168.1.255'}, {'type': 'INET6', 'address': 'fe80::baca:3aff:fe84:b804', 'netmask': 64, 'broadcast': 'fe80::ffff:ffff:ffff:ffff'}], 'vrrp_config': None}, 'aliases': [], 'ipv4_dhcp': True, 'ipv6_auto': False, 'description': '', 'mtu': None}]
2022-12-01 20:33:57.142 DEBUG (SyncWorker_8) [custom_components.truenas.apiparser] Processing source [{'id': 'enp0s25', 'name': 'enp0s25', 'fake': False, 'type': 'PHYSICAL', 'state': {'name': 'enp0s25', 'orig_name': 'enp0s25', 'description': 'enp0s25', 'mtu': 1500, 'cloned': False, 'flags': ['MULTICAST', 'UP', 'BROADCAST'], 'nd6_flags': ['HOMEADDRESS'], 'capabilities': ['tx-scatter-gather', 'tx-checksum-ip-generic', 'tx-vlan-hw-insert', 'rx-vlan-hw-parse', 'tx-generic-segmentation', 'rx-gro', 'tx-tcp-segmentation', 'tx-tcp6-segmentation', 'rx-hashing', 'rx-checksum'], 'link_state': 'LINK_STATE_UP', 'media_type': 'Ethernet', 'media_subtype': 'autoselect', 'active_media_type': 'Ethernet', 'active_media_subtype': '1000Mb/s Twisted Pair', 'supported_media': ['10baseT/Half', '10baseT/Full', '100baseT/Half', '100baseT/Full', '1000baseT/Full'], 'media_options': None, 'link_address': 'b8:ca:3a:84:b8:04', 'aliases': [{'type': 'LINK', 'address': 'b8:ca:3a:84:b8:04'}, {'type': 'INET', 'address': '192.168.1.166', 'netmask': 24, 'broadcast': '192.168.1.255'}, {'type': 'INET6', 'address': 'fe80::baca:3aff:fe84:b804', 'netmask': 64, 'broadcast': 'fe80::ffff:ffff:ffff:ffff'}], 'vrrp_config': None}, 'aliases': [], 'ipv4_dhcp': True, 'ipv6_auto': False, 'description': '', 'mtu': None}]
2022-12-01 20:33:57.142 DEBUG (SyncWorker_8) [custom_components.truenas.apiparser] Processing entry {'id': 'enp0s25', 'name': 'enp0s25', 'fake': False, 'type': 'PHYSICAL', 'state': {'name': 'enp0s25', 'orig_name': 'enp0s25', 'description': 'enp0s25', 'mtu': 1500, 'cloned': False, 'flags': ['MULTICAST', 'UP', 'BROADCAST'], 'nd6_flags': ['HOMEADDRESS'], 'capabilities': ['tx-scatter-gather', 'tx-checksum-ip-generic', 'tx-vlan-hw-insert', 'rx-vlan-hw-parse', 'tx-generic-segmentation', 'rx-gro', 'tx-tcp-
2022-12-01 20:33:57.144 DEBUG (SyncWorker_3) [custom_components.truenas.truenas_api] TrueNAS 192.168.1.166:444 query: reporting/get_data, post, {'graphs': [{'name': 'load'}, {'name': 'cputemp'}, {'name': 'cpu'}, {'name': 'arcsize'}, {'name': 'arcratio'}, {'name': 'memory'}, {'name': 'interface', 'identifier': 'enp0s25'}], 'reporting_query': {'start': 'now-90s', 'end': 'now-30s', 'aggregate': True}}
2022-12-01 20:33:57.897 DEBUG (SyncWorker_3) [custom_components.truenas.truenas_api] TrueNAS 192.168.1.166:444 query response: [{'name': 'load', 'identifier': None, 'data': [[None, None, None], [None, None, None], [None, None, None], [None, None, None], [None, None, None], [None, None, None], [None, None, None]], 'start': 1669923150, 'end': 1669923210, 'step': 10, 'legend': ['load_shortterm', 'load_midterm', 'load_longterm'], 'aggregations': {'min': [None, None, None], 'mean': [None, None, None], 'max': [None, None, None]}}, {'name': 'cputemp', 'identifier': None, 'data': [[None, None, None, None], [None, None, None, None], [None, None, None, None], [None, None, None, None], [None, None, None, None], [None, None, None, None], [None, None, None, None]], 'start': 1669923150, 'end': 1669923210, 'step': 10, 'legend': ['cputemp0', 'cputemp1', 'cputemp2', 'cputemp3'], 'aggregations': {'min': [None, None, None, None], 'mean': [None, None, None, None], 'max': [None, None, None, None]}}, {'name': 'cpu', 'identifier': None, 'data': [[None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None]], 'start': 1669923150, 'end': 1669923210, 'step': 10, 'legend': ['interrupt', 'system', 'user', 'nice', 'idle'], 'aggregations': {'min': [None, None, None, None, None], 'mean': [None, None, None, None, None], 'max': [None, None, None, None, None]}}, {'name': 'arcsize', 'identifier': None, 'data': [[None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None]], 'start': 1669923150, 'end': 1669923210, 'step': 10, 'legend': ['cache_size-arc_value', 'cache_size-L2_value'], 'aggregations': {'min': [None, None], 'mean': [None, None], 'max': [None, None]}}, {'name': 'arcratio', 'identifier': None, 'data': [[None, None], [None, None], [None, None], [None, None], [None, None], [None, None], [None, None]], 'start': 1669923150, 'end': 1669923210, 'step': 10, 'legend': ['cache_ratio-arc_value', 'cache_ratio-L2_value'], 'aggregations': {'min': [None, None], 'mean': [None, None], 'max': [None, None]}}, {'name': 'memory', 'identifier': None, 'data': [[None, None, None, None], [None, None, None, None], [None, None, None, None], [None, None, None, None], [None, None, None, None], [None, None, None, None], [None, None, None, None]], 'start': 1669923150, 'end': 1669923210, 'step': 10, 'legend': ['memory-used_value', 'memory-free_value', 'memory-cached_value', 'memory-buffered_value'], 'aggregations': {'min': [None, None, None, None], 'mean': [None, None, None, None], 'max': [None, None, None, None]}}, {'name': 'interface', 'identifier': 'enp0s25', 'data': [[None, None, None], [None, None, None], [None, None, None], [None, None, None], [None, None, None], [None, None, None], [None, None, None]], 'start': 1669923150, 'end': 1669923210, 'step': 10, 'legend': ['rx', 'tx', 'overlap'], 'aggregations': {'min': [None, None, None], 'mean': [None, None, None], 'max': [None, None, None]}}]
2022-12-01 20:33:57.899 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/truenas/truenas_controller.py", line 110, in force_update
    await self.async_update()
  File "/config/custom_components/truenas/truenas_controller.py", line 124, in async_update
    await self.hass.async_add_executor_job(self.get_systemstats)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/truenas/truenas_controller.py", line 388, in get_systemstats
    max(list(filter(None, tmp_graph[i]["aggregations"]["mean"]))), 1
ValueError: max() arg is an empty sequence

**Comment by UhtredTheBold** [comment]
I've been seeing this as well. My system is powered off most of the time and I power it on with WOL

**Comment by kilem86** [comment]
Another with the same behaivour, Usually my server is off all the time, and I turn on by WOL when I need something, or do some maintenance jobs, and sometimes the integration charge the details, but another times not. So... the automations sometimes doesn´t work well.

I having this issue for long time ago

**Comment by UhtredTheBold** [comment]
I've recently started calling the reload_config_entry service to restart the integration once my truenas server comes online. I've no failures for weeks now.

**Comment by kilem86** [comment]
That true @UhtredTheBold I just did with my configuration, and now it looks fine! Thank you so much for the advice! Great

**Comment by tomaae** [comment]
already fixed
