### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Geeboh** [tomaae/homeassistant-truenas#55]
## Describe the issue
Plugin fails to start with message: Failed to set up

## How to reproduce the issue

1. Install
2. Add integration
3. Enter:
- Name
- Host IP
- API Key
- [ ] Use SSL
- [ ] Verify SSL certificate
4. Click Submit

## Screenshots
![image](https://user-images.githubusercontent.com/69756825/201500414-2bd6ddcf-1848-42fe-9dca-e46f8f959f8c.png)

## Software versions

 **- Home Assistant version:**
  **_Home Assistant:_** 2022.11.2
  **_Supervisor:_** 2022.10.2
  **_Operating System:_** 9.3
  **_Frontend:_** 20221108.0 - latest
 - HACS version: 1.28.3
 - TrueNAS integration version: v1.2.3 -->
 - TrueNAS version: TrueNAS-SCALE-22.02.4

## Diagnostics data
N/A

## Traceback/Error logs
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/truenas/truenas_controller.py:388
Integration: TrueNAS (documentation, issues)
First occurred: 11:45:49 AM (1 occurrences)
Last logged: 11:45:49 AM

Error setting up entry TrueNAS for truenas
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/truenas/__init__.py", line 29, in async_setup_entry
    await controller.async_update()
  File "/config/custom_components/truenas/truenas_controller.py", line 124, in async_update
    await self.hass.async_add_executor_job(self.get_systemstats)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/truenas/truenas_controller.py", line 388, in get_systemstats
    max(list(filter(None, tmp_graph[i]["aggregations"]["mean"]))), 1
ValueError: max() arg is an empty sequence

## Additional context
Looks like this is another case of not sanitizing input values before performing operations on them.

**Comment by Geeboh** [comment]
Might be an issue with how filter is being used to remove "none" (nulls)

[Python: filter(None, [list of bools]) behavior](https://stackoverflow.com/questions/38339496/python-filternone-list-of-bools-behavior)](https://stackoverflow.com/a/38339539)

**Comment by Geeboh** [comment]
Tested this by manually changing:
`max(list(filter(None, tmp_graph[i]["aggregations"]["mean"]))), 1`
to:
`max(list(filter(lambda x: x is not None, tmp_graph[i]["aggregations"]["mean"]))), 1`

**Comment by tomaae** [comment]
Filter actually works as intended there.
Its max that is causing issue here because list is empty. That was not a case before, so something changed in python.
That also means, lambda you used puts something into the list, which is not good.

I will have to take a look into what changed in max function.

**Comment by Geeboh** [comment]
The other option could be to give max a default:
`max(list(filter(None, tmp_graph[i]["aggregations"]["mean"])), default=None), 1`

**Comment by tomaae** [comment]
That would be giving wrong info tho. I want sensor to enter null state if there is no data.
That way sensor can be marked at not available in HA too.

**Comment by Geeboh** [comment]
Would setting the default to none fix this?
`max(list(filter(None, tmp_graph[i]["aggregations"]["mean"])), default=None), 1`
